"""
LangGraph Multi-Agent Architecture: Memory/Ontology DeepAgent + Execution DeepAgent
===================================================================================
A two-tier DeepAgent workflow implemented with LangGraph and powered by local
Subscription Reverse Proxy (`http://127.0.0.1:8000/v1`).

Architecture Overview:
----------------------
1. 🧠 DeepAgent 1 (Memory & Ontology Agent - "The Knowledge Architect"):
   - Maintains persistent knowledge graph (entities & relations) and episodic memory.
   - Phase 1 (Planning): Entity linking, context retrieval, and generates a structured Directive Contract.
   - Phase 2 (Reflection): Analyzes execution evidence, extracts new triples, updates the ontology, and synthesizes final response.

2. ⚙️ DeepAgent 2 (Execution Agent - "The Tool Operator"):
   - Receives the Directive from DeepAgent 1.
   - Dispatches and coordinates specialized subagents/tools:
     * Math & Calculation Subagent
     * Python Code Execution Subagent
     * Lab Knowledge Base Subagent
     * System & Runtime Inspection Subagent
   - Synthesizes raw execution evidence and reports back to DeepAgent 1.

3. 🔄 LangGraph State Machine:
   [START] -> memory_planner -> execution_engine -> memory_reflector -> [END]
"""

import argparse
import datetime
import json
import logging
import math
import os
import platform
import re
import sys
from typing import Annotated, Any, Dict, List, Optional, Tuple, TypedDict

from langchain_core.messages import AIMessage, BaseMessage, HumanMessage, SystemMessage
from langchain_openai import ChatOpenAI
from langgraph.graph import END, START, StateGraph
from langgraph.graph.message import add_messages
from pydantic import BaseModel, Field

logging.basicConfig(level=logging.WARNING)
logger = logging.getLogger("deepagents-graph")


# ---------------------------------------------------------
# 1. State & Ontology Data Models
# ---------------------------------------------------------
class DeepAgentState(TypedDict):
    """Global shared state flowing across the LangGraph nodes."""
    messages: Annotated[List[BaseMessage], add_messages]
    user_goal: str
    ontology: Dict[str, Any]          # {"entities": {id: Entity}, "triples": [Triple]}
    memory: Dict[str, Any]            # {"episodic": [...], "working": {...}}
    directive: Dict[str, Any]         # Generated by Memory Agent for Execution Agent
    execution_trace: List[str]        # Log of subagent steps & tool outputs
    execution_result: Dict[str, Any]  # Result output from Execution Agent
    reflection: Dict[str, Any]        # Discovered facts & state delta
    final_output: str                 # User-facing synthesized answer
    iteration_count: int


# ---------------------------------------------------------
# 2. Initial Seed Knowledge Graph (Graph Engineering Lab)
# ---------------------------------------------------------
def create_initial_ontology() -> Dict[str, Any]:
    """Foundational domain ontology for graph engineering and agent workflows."""
    return {
        "entities": {
            "LangGraph": {
                "name": "LangGraph",
                "type": "Framework",
                "description": "Library for building stateful, multi-agent applications with cyclic graph architectures.",
                "attributes": {"ecosystem": "LangChain", "paradigm": "Cyclic State Machine"},
            },
            "DeepAgent": {
                "name": "DeepAgent",
                "type": "ArchitecturePattern",
                "description": "Autonomous agent pattern featuring internal state, planning, memory synthesis, and subagent orchestration.",
                "attributes": {"characteristics": ["Stateful", "Reflective", "Hierarchical"]},
            },
            "KnowledgeGraph": {
                "name": "KnowledgeGraph",
                "type": "DataStructure",
                "description": "Graph-structured knowledge base representing entities and their semantic relationships as triples.",
                "attributes": {"format": "Labeled Property Graph / Triples", "query_language": "Cypher/SPARQL"},
            },
            "GraphRAG": {
                "name": "GraphRAG",
                "type": "Methodology",
                "description": "Retrieval-Augmented Generation enhanced by knowledge graphs for multi-hop semantic reasoning.",
                "attributes": {"benefits": ["Context-aware", "Structured", "Multi-hop reasoning"]},
            },
            "SubscriptionProxy": {
                "name": "SubscriptionProxy",
                "type": "Infrastructure",
                "description": "Reverse-authenticated local proxy exposing OpenAI/Anthropic subscription APIs to agent frameworks.",
                "attributes": {"port": 8000, "protocol": "OpenAI ChatCompletions"},
            },
        },
        "triples": [
            {"subject": "LangGraph", "predicate": "implements", "object": "DeepAgent"},
            {"subject": "DeepAgent", "predicate": "manages", "object": "KnowledgeGraph"},
            {"subject": "GraphRAG", "predicate": "leverages", "object": "KnowledgeGraph"},
            {"subject": "DeepAgent", "predicate": "communicates_via", "object": "SubscriptionProxy"},
        ],
    }


# ---------------------------------------------------------
# 3. Subagent Tools for DeepAgent 2 (Execution Agent)
# ---------------------------------------------------------
class SubagentTools:
    """Specialized action tools dispatched by the Execution Agent."""

    @staticmethod
    def calculate(expression: str) -> str:
        """Evaluates mathematical expressions safely."""
        allowed = {
            "math": math,
            "abs": abs,
            "round": round,
            "min": min,
            "max": max,
            "sum": sum,
            "pow": pow,
            "sqrt": math.sqrt,
            "log": math.log,
            "pi": math.pi,
            "e": math.e,
        }
        try:
            clean = expression.strip().strip("'\"")
            # Replace ^ with ** for intuitive power operation
            clean = re.sub(r"(?<=\d|\))\s*\^\s*(?=\d|\()", " ** ", clean)
            val = eval(clean, {"__builtins__": {}}, allowed)
            return f"Result: {val}"
        except Exception as e:
            return f"Calculation error: {e}"

    @staticmethod
    def python_eval(code: str) -> str:
        """Executes a Python snippet and captures output or returned expressions."""
        import io
        import contextlib

        stdout_buf = io.StringIO()
        clean_code = code.strip().strip("`")
        if clean_code.startswith("python\n"):
            clean_code = clean_code[7:]

        local_vars: Dict[str, Any] = {"math": math, "json": json}
        try:
            with contextlib.redirect_stdout(stdout_buf):
                try:
                    expr_val = eval(clean_code, {"__builtins__": __builtins__}, local_vars)
                    if expr_val is not None:
                        print(expr_val)
                except SyntaxError:
                    exec(clean_code, {"__builtins__": __builtins__}, local_vars)
            output = stdout_buf.getvalue().strip()
            return output if output else "Execution successful (no stdout)."
        except Exception as e:
            return f"Python execution error: {e}"

    @staticmethod
    def system_inspect(query: str) -> str:
        """Inspects system runtime, OS details, Python environment, or timestamps."""
        q = query.lower()
        now_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        if "time" in q or "date" in q:
            return f"Local Time: {now_str}"
        elif "python" in q:
            return f"Python {platform.python_version()} on {sys.executable}"
        elif "os" in q or "platform" in q:
            return f"OS: {platform.system()} {platform.release()} ({platform.machine()})"
        return f"System Info: {platform.system()} {platform.machine()} | Python {platform.python_version()} | Time: {now_str}"

    @staticmethod
    def lab_knowledge(query: str) -> str:
        """Queries the Graph Engineering Lab internal registry for domain topics."""
        db = {
            "graphrag": "GraphRAG uses hierarchical graph indexing (communities) to summarize and extract insights across corpora.",
            "neo4j": "Graph database using Cypher property graph model, widely used for enterprise knowledge graphs.",
            "langgraph": "Stateful graph engine with nodes, edges, checkpointing, and human-in-the-loop agent patterns.",
            "deepagents": "Multi-agent systems where high-level cognitive tasks (memory, ontology) are segregated from actuation.",
        }
        for k, v in db.items():
            if k in query.lower():
                return f"[{k.upper()}]: {v}"
        return f"No specialized lab entry for '{query}'. Available entries: {', '.join(db.keys())}"


# ---------------------------------------------------------
# Helper: Robust JSON Extractor
# ---------------------------------------------------------
def extract_json(raw_text: str) -> Dict[str, Any]:
    """Safely extracts JSON even if surrounded by markdown code blocks or conversational text."""
    clean = raw_text.strip()
    if clean.startswith("```"):
        lines = clean.splitlines()
        if lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        clean = "\n".join(lines).strip()

    try:
        return json.loads(clean)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", clean, re.DOTALL)
        if match:
            return json.loads(match.group(0))
        raise ValueError(f"Could not parse valid JSON from text: {raw_text[:200]}...")


# ---------------------------------------------------------
# 4. DeepAgents LangGraph Workflow Class
# ---------------------------------------------------------
class DeepAgentsWorkflow:
    """Encapsulates the multi-agent cognitive architecture and LangGraph graph."""

    def __init__(self, llm: ChatOpenAI):
        self.llm = llm

    def memory_plan_node(self, state: DeepAgentState) -> Dict[str, Any]:
        """
        DeepAgent 1 (The Architect - Phase 1):
        - Analyzes user goal and retrieves relevant context from active ontology.
        - Produces a formal Directive Contract for DeepAgent 2.
        """
        user_goal = state["user_goal"]
        ontology = state["ontology"]
        memory = state.get("memory", {})

        print("\n" + "═" * 75)
        print("🧠 [DeepAgent 1: Memory & Ontology Agent] -> PHASE 1: PLANNING & CONTEXT RETRIEVAL")
        print("═" * 75)

        prompt = f"""You are DeepAgent 1 (The Memory & Ontology Architect) in a multi-agent system.
Your mission is to analyze the user goal, consult the current domain ontology, and formulate a precise Directive Contract for DeepAgent 2 (The Execution Agent).

CURRENT ONTOLOGY ENTITIES:
{json.dumps(list(ontology['entities'].keys()), indent=2)}

CURRENT ONTOLOGY TRIPLES:
{json.dumps(ontology['triples'], indent=2)}

PAST EPISODIC MEMORY:
{json.dumps(memory.get('episodic', []), indent=2)}

USER GOAL:
"{user_goal}"

Respond with ONLY a JSON object formatted as:
{{
  "identified_concepts": ["list of entities relevant to this goal"],
  "ontology_context_summary": "brief summary of relevant relationships already known",
  "execution_objective": "concise, unambiguous instruction for the execution agent",
  "required_tool_actions": ["list of tools/subagents that should be used, e.g. calculate, python_eval, system_inspect, lab_knowledge"],
  "constraints": ["rules the execution agent must adhere to"]
}}"""

        response = self.llm.invoke([
            SystemMessage(content="You are an expert Ontology Architect. Output ONLY valid JSON."),
            HumanMessage(content=prompt),
        ])

        try:
            plan_data = extract_json(response.content)
        except Exception as e:
            logger.warning(f"Fallback plan parsing: {e}")
            plan_data = {
                "identified_concepts": [],
                "ontology_context_summary": "Domain query analysis",
                "execution_objective": user_goal,
                "required_tool_actions": ["calculate", "python_eval"],
                "constraints": ["Provide exact numbers and evidence"],
            }

        print(f"📌 Identified Concepts : {plan_data.get('identified_concepts')}")
        print(f"🎯 Execution Objective : {plan_data.get('execution_objective')}")
        print(f"🛠️  Required Subagents  : {plan_data.get('required_tool_actions')}")

        directive = {
            "objective": plan_data.get("execution_objective", user_goal),
            "target_tools": plan_data.get("required_tool_actions", []),
            "constraints": plan_data.get("constraints", []),
            "domain_hints": plan_data.get("ontology_context_summary", ""),
            "timestamp": datetime.datetime.now().isoformat(),
        }

        return {
            "directive": directive,
            "execution_trace": [f"[MemoryAgent] Formulated Directive: {directive['objective']}"],
        }

    def execution_engine_node(self, state: DeepAgentState) -> Dict[str, Any]:
        """
        DeepAgent 2 (The Operator):
        - Dispatches subagent tools according to the Directive.
        - Compiles observations and reports findings.
        """
        directive = state["directive"]
        user_goal = state["user_goal"]

        print("\n" + "─" * 75)
        print("⚙️  [DeepAgent 2: Execution Agent] -> EXECUTING DIRECTIVE CONTRACT")
        print("─" * 75)
        print(f"📥 Received Directive: {directive['objective']}")

        tools_manifest = """
Available Subagents/Tools:
1. calculate(expression: str) -> Safe arithmetic evaluation (e.g. '15000 * 128 / (1024 * 1024)')
2. python_eval(code: str) -> Run arbitrary Python algorithms, graph math, data transformations
3. system_inspect(query: str) -> Check runtime OS, Python version, local time
4. lab_knowledge(query: str) -> Query Graph Engineering Lab definitions (GraphRAG, Neo4j, etc.)
"""

        prompt = f"""You are DeepAgent 2 (The Execution Agent).
You received the following Directive from DeepAgent 1 (The Memory & Ontology Architect):

DIRECTIVE:
"{directive['objective']}"

ORIGINAL USER GOAL:
"{user_goal}"

CONSTRAINTS:
{json.dumps(directive.get('constraints', []), indent=2)}

{tools_manifest}

Plan and execute the required subagent actions.
Output ONLY a JSON list of tool invocations to run:
[
  {{"tool": "calculate" | "python_eval" | "system_inspect" | "lab_knowledge", "input": "argument string"}}
]"""

        response = self.llm.invoke([
            SystemMessage(content="You are a precise execution agent. Output ONLY a valid JSON list."),
            HumanMessage(content=prompt),
        ])

        tool_calls = []
        try:
            raw_clean = response.content.strip()
            if raw_clean.startswith("```"):
                lines = raw_clean.splitlines()
                if lines[0].startswith("```"):
                    lines = lines[1:]
                if lines and lines[-1].strip() == "```":
                    lines = lines[:-1]
                raw_clean = "\n".join(lines).strip()
            parsed = json.loads(raw_clean)
            if isinstance(parsed, list):
                tool_calls = parsed
            elif isinstance(parsed, dict) and "tool" in parsed:
                tool_calls = [parsed]
        except Exception as e:
            logger.warning(f"Error parsing tool calls: {e}")

        trace = list(state.get("execution_trace", []))
        observations = []

        for call in tool_calls:
            t_name = call.get("tool", "")
            t_input = str(call.get("input", ""))
            print(f"🔧 Invoking Subagent [{t_name}] with input: {t_input}")

            if t_name == "calculate":
                res = SubagentTools.calculate(t_input)
            elif t_name == "python_eval":
                res = SubagentTools.python_eval(t_input)
            elif t_name == "system_inspect":
                res = SubagentTools.system_inspect(t_input)
            elif t_name == "lab_knowledge":
                res = SubagentTools.lab_knowledge(t_input)
            else:
                res = f"Unknown tool '{t_name}'"

            print(f"   ↳ Observation: {res}")
            observations.append({"tool": t_name, "input": t_input, "output": res})
            trace.append(f"[ExecAgent:{t_name}] In: {t_input} -> Out: {res}")

        # Synthesize findings
        synthesis_prompt = f"""You are DeepAgent 2. You have executed tools for the Directive: "{directive['objective']}".

OBSERVATIONS & EVIDENCE:
{json.dumps(observations, indent=2)}

Summarize your findings in a structured JSON report:
{{
  "evidence_summary": "detailed explanation of findings with factual data",
  "derived_facts": ["list of concrete, atomic statements or facts discovered"],
  "status": "completed"
}}"""

        synth_resp = self.llm.invoke([
            SystemMessage(content="Output ONLY valid JSON report."),
            HumanMessage(content=synthesis_prompt),
        ])

        try:
            report = extract_json(synth_resp.content)
        except Exception:
            report = {
                "evidence_summary": "\n".join(f"{o['tool']}: {o['output']}" for o in observations),
                "derived_facts": [str(o["output"]) for o in observations],
                "status": "completed",
            }

        return {
            "execution_result": report,
            "execution_trace": trace,
            "iteration_count": state.get("iteration_count", 0) + 1,
        }

    def memory_reflect_node(self, state: DeepAgentState) -> Dict[str, Any]:
        """
        DeepAgent 1 (The Architect - Phase 2):
        - Ingests empirical observations from DeepAgent 2.
        - Discovers new entities and relationship triples.
        - Mutates the Knowledge Graph ontology.
        - Records episodic lessons and delivers final response.
        """
        user_goal = state["user_goal"]
        ontology = dict(state["ontology"])
        memory = dict(state.get("memory", {}))
        execution_result = state["execution_result"]

        print("\n" + "═" * 75)
        print("🧠 [DeepAgent 1: Memory & Ontology Agent] -> PHASE 2: REFLECTION & ONTOLOGY EVOLUTION")
        print("═" * 75)

        prompt = f"""You are DeepAgent 1 (The Memory & Ontology Architect).
The Execution Agent has completed its mission and reported empirical evidence.
Your task is to:
1. Synthesize the final comprehensive answer for the user.
2. Extract new entities and Knowledge Graph triples (Subject - Predicate - Object) discovered during this task.
3. Formulate an episodic memory entry summarizing what was learned.

USER GOAL:
"{user_goal}"

EXECUTION EVIDENCE & FACTS:
{json.dumps(execution_result, indent=2)}

EXISTING ONTOLOGY TRIPLES:
{json.dumps(ontology.get('triples', []), indent=2)}

Respond with ONLY a JSON object:
{{
  "final_answer": "Complete, structured, and polished final answer to the user goal",
  "new_entities": [
    {{"name": "...", "type": "...", "description": "..."}}
  ],
  "new_triples": [
    {{"subject": "...", "predicate": "...", "object": "..."}}
  ],
  "episodic_lesson": "Brief lesson learned or decision captured for long-term memory"
}}"""

        response = self.llm.invoke([
            SystemMessage(content="You are an expert Ontology Architect. Output ONLY valid JSON."),
            HumanMessage(content=prompt),
        ])

        try:
            reflection_data = extract_json(response.content)
        except Exception as e:
            logger.warning(f"Error parsing reflection JSON: {e}")
            reflection_data = {
                "final_answer": execution_result.get("evidence_summary", "Task executed."),
                "new_entities": [],
                "new_triples": [],
                "episodic_lesson": f"Executed goal: {user_goal}",
            }

        # Update Ontology Entities
        for ent in reflection_data.get("new_entities", []):
            name = ent.get("name")
            if name and name not in ontology["entities"]:
                ontology["entities"][name] = {
                    "name": name,
                    "type": ent.get("type", "Entity"),
                    "description": ent.get("description", ""),
                    "attributes": {"discovered_at": datetime.datetime.now().isoformat()},
                }
                print(f"✨ [Ontology Growth] Added Entity: {name} ({ent.get('type')})")

        # Update Ontology Triples
        existing_triple_keys = {
            (t["subject"].lower(), t["predicate"].lower(), t["object"].lower())
            for t in ontology.get("triples", [])
        }

        added_triples = []
        for trip in reflection_data.get("new_triples", []):
            s, p, o = trip.get("subject", ""), trip.get("predicate", ""), trip.get("object", "")
            if s and p and o:
                key = (s.lower(), p.lower(), o.lower())
                if key not in existing_triple_keys:
                    triple_obj = {"subject": s, "predicate": p, "object": o}
                    ontology["triples"].append(triple_obj)
                    existing_triple_keys.add(key)
                    added_triples.append(triple_obj)
                    print(f"🔗 [Ontology Growth] Added Triple: ({s}) ──[:{p}]──> ({o})")

        # Update Episodic Memory
        episodic_list = list(memory.get("episodic", []))
        episodic_list.append({
            "goal": user_goal,
            "lesson": reflection_data.get("episodic_lesson", ""),
            "timestamp": datetime.datetime.now().isoformat(),
            "triples_added": len(added_triples),
        })
        memory["episodic"] = episodic_list

        final_answer = reflection_data.get("final_answer", "")

        return {
            "ontology": ontology,
            "memory": memory,
            "reflection": reflection_data,
            "final_output": final_answer,
        }

    def compile_graph(self):
        """Builds and compiles the LangGraph StateGraph."""
        workflow = StateGraph(DeepAgentState)

        workflow.add_node("memory_planner", self.memory_plan_node)
        workflow.add_node("execution_engine", self.execution_engine_node)
        workflow.add_node("memory_reflector", self.memory_reflect_node)

        workflow.add_edge(START, "memory_planner")
        workflow.add_edge("memory_planner", "execution_engine")
        workflow.add_edge("execution_engine", "memory_reflector")
        workflow.add_edge("memory_reflector", END)

        return workflow.compile()


# ---------------------------------------------------------
# 5. Visualization & CLI Tools
# ---------------------------------------------------------
def display_ontology_graph(ontology: Dict[str, Any]):
    """Pretty prints the Knowledge Graph / Ontology."""
    print("\n" + "┌" + "─" * 70 + "┐")
    print("│" + " 🕸️  ACTIVE DOMAIN ONTOLOGY (KNOWLEDGE GRAPH) ".center(70) + "│")
    print("├" + "─" * 70 + "┤")
    print(f"│ Entities ({len(ontology['entities'])}):")
    for k, v in ontology["entities"].items():
        desc = v.get("description", "")
        if len(desc) > 36:
            desc = desc[:33] + "..."
        print(f"│   • {k:<22} [{v.get('type', 'Concept')}] : {desc}")
    print("│")
    print(f"│ Semantic Triples ({len(ontology['triples'])}):")
    for t in ontology["triples"]:
        print(f"│   • ({t['subject']}) ──[:{t['predicate']}]──> ({t['object']})")
    print("└" + "─" * 70 + "┘\n")


def print_mermaid():
    """Outputs Mermaid diagram of the DeepAgent workflow."""
    print("""```mermaid
flowchart TD
    Start([User Query / Goal]) --> MP[DeepAgent 1: Memory Planner]
    
    subgraph DeepAgent1_Plan["🧠 DeepAgent 1: Memory & Ontology (Phase 1)"]
        MP -->|Entity Linking & Context Retrieval| Dir[Directive Contract Formulation]
    end
    
    Dir -->|Contract + Constraints| EE[DeepAgent 2: Execution Engine]
    
    subgraph DeepAgent2_Exec["⚙️ DeepAgent 2: Execution & Subagents"]
        EE --> SubCalc[Math Subagent]
        EE --> SubPy[Python Code Subagent]
        EE --> SubSys[System Subagent]
        EE --> SubKB[Lab Knowledge Subagent]
    end
    
    SubCalc --> Evidence[Empirical Evidence Synthesis]
    SubPy --> Evidence
    SubSys --> Evidence
    SubKB --> Evidence
    
    Evidence --> MR[DeepAgent 1: Memory Reflector]
    
    subgraph DeepAgent1_Reflect["🧠 DeepAgent 1: Reflection & Learning (Phase 2)"]
        MR --> Extract[Triplet & Entity Extraction]
        Extract --> KG[(Ontology Knowledge Graph)]
        Extract --> Mem[(Episodic Memory)]
    end
    
    MR --> Final([Synthesized Final Answer])
```""")


def run_goal(app, goal: str, initial_ontology: Optional[Dict[str, Any]] = None):
    """Executes a single user goal through the compiled LangGraph workflow."""
    ontology = initial_ontology or create_initial_ontology()

    initial_state: DeepAgentState = {
        "messages": [HumanMessage(content=goal)],
        "user_goal": goal,
        "ontology": ontology,
        "memory": {"episodic": [], "working": {}},
        "directive": {},
        "execution_trace": [],
        "execution_result": {},
        "reflection": {},
        "final_output": "",
        "iteration_count": 0,
    }

    print("\n" + "★" * 75)
    print(f"🚀 INITIATING DEEPAGENTS WORKFLOW FOR GOAL:\n   \"{goal}\"")
    print("★" * 75)

    result_state = app.invoke(initial_state)

    print("\n" + "═" * 75)
    print("💡 FINAL ANSWER DELIVERED BY DEEPAGENT 1:")
    print("═" * 75)
    print(result_state["final_output"])
    print("═" * 75)

    display_ontology_graph(result_state["ontology"])
    return result_state


def main():
    parser = argparse.ArgumentParser(description="DeepAgents LangGraph Multi-Agent Workflow")
    parser.add_argument("--endpoint", default="http://127.0.0.1:8000/v1", help="Subscription Proxy URL")
    parser.add_argument("--model", default="codex", choices=["codex", "claude", "gpt-6-sol", "claude-haiku-4-5-20251001"])
    parser.add_argument("--query", type=str, default=None, help="Single query to run")
    parser.add_argument("--test", action="store_true", help="Run multi-step study benchmark")
    parser.add_argument("--mermaid", action="store_true", help="Print Mermaid flowchart diagram")
    args = parser.parse_args()

    if args.mermaid:
        print_mermaid()
        return

    print("=" * 70)
    print("🤖 Compiling DeepAgents LangGraph Workflow...")
    print(f"   LLM Proxy Endpoint : {args.endpoint}")
    print(f"   Selected Model     : {args.model}")
    print("=" * 70)

    llm = ChatOpenAI(
        base_url=args.endpoint,
        api_key="subscription-proxy",
        model=args.model,
        temperature=0.0,
        use_responses_api=False,
    )

    workflow_mgr = DeepAgentsWorkflow(llm=llm)
    app = workflow_mgr.compile_graph()

    if args.test:
        test_goal = (
            "Analyze GraphRAG within our Graph Engineering Lab. Calculate the memory required for 15,000 "
            "entities if each node record takes 128 bytes, convert to megabytes (divide by 1024 * 1024), "
            "and check our runtime OS and local time."
        )
        run_goal(app, test_goal)
        return

    if args.query:
        run_goal(app, args.query)
        return

    # Interactive Studio Loop
    ontology = create_initial_ontology()
    print("\n" + "=" * 65)
    print("Interactive DeepAgents Studio Ready.")
    print("Type a complex question or goal to watch the agents think, act, and learn.")
    print("Type 'graph' to inspect ontology, 'exit' to quit.")
    print("=" * 65)

    while True:
        try:
            user_input = input("\n🎯 Goal: ").strip()
            if not user_input:
                continue
            if user_input.lower() in ("exit", "quit", "q"):
                print("Exiting.")
                break
            if user_input.lower() == "graph":
                display_ontology_graph(ontology)
                continue

            state = run_goal(app, user_input, initial_ontology=ontology)
            ontology = state["ontology"]  # Carry forward evolved ontology
        except (KeyboardInterrupt, EOFError):
            print("\nExiting.")
            break


if __name__ == "__main__":
    main()
